# Generated by Django 5.1.4 on 2024-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrank_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('member', 'Member')], default='member', max_length=255, verbose_name='Role'),
        ),
    ]
